[Lan]
String_tabControl1_TabPages0=基本设置
String_tabControl1_TabPages1=二维码设置
String_tabControl1_TabPages2=韦根和读卡设置
String_tabControl1_TabPages3=身份证操作
String_tabControl1_TabPages4=读头操作
String_tabControl1_TabPages5=一体机参数
String_tabControl1_TabPages6=发卡操作
String_tabControl1_TabPages7=固件升级

String_tabControl2_TabPages0=Mifare用户卡操作
String_tabControl2_TabPages1=CPU用户卡操作
String_tabControl2_TabPages2=CPU配置卡操作

String_buttonClear=清除


;tabPage1

String_buttonConnect=连接
String_buttonDisConnect=断开
String_buttonSacningAddress=扫描地址

String_buttonFactorySetting=出厂设置
String_buttonGetVersion=读版本号
String_buttonWrtiteConfig4=写配置
String_buttonReadConfig4=读配置

String_buttonVerify152=控制模式
String_buttonPolling=验证模式

String_buttonAutoPolling=轮询间隔
String_buttonStop=停止

String_labelPort=端口
String_labelSecond1=秒

String_comboBoxJINZHI0=十进制
String_comboBoxJINZHI1=十六进制
String_comboBoxJINZHI2=BCD格式

String_comboBoxKG4850=RS485 关闭
String_comboBoxKG4851=RS485 打开

String_comboBoxKGHID0=HID 键盘关闭
String_comboBoxKGHID1=HID 键盘打开



String_comboBoxControlMode0=验证成功
String_comboBoxControlMode1=无权限
String_comboBoxControlMode2=验证失败

String_labelRS485Address=RS485地址
String_labelwriteaddress=写入RS485地址
String_labelOpenDoorTime=开门时间

String_labelControlMode=控制模式
String_labelValidationMode=验证模式
String_labelPollingInterval=轮询间隔

String_comboBoxAuthMode0=卡数据
String_comboBoxAuthMode1=二维码数据
String_comboBoxAuthMode2=卡和二维码数据
String_comboBoxAuthMode3=卡或二维码数据



;tabPage2

String_comboBoxDIDMode0=不输出DID
String_comboBoxDIDMode1=输出DID

String_WriteConfig=写配置
String_ReadConfig=读配置

String_labelDecodeKey=二维码解码秘钥
String_labelQRTime=二维码有效时间
String_labelSecond=秒
String_labelQRMode=二维码模式

String_comboBoxQRMode0=不加密透传
String_comboBoxQRMode1=加密传输
String_comboBoxQRMode2=定制加密模式


;tabPage3

String_labelX10us=X 10 微秒
String_String_labelX100A1000us=X 100 + 1000 微秒

String_labelUserKey3=用户卡密钥

String_labelFileID3=文件编号(十进制)
String_labelDFID3=DF ID(16进制)


String_labelStartBlock3=起始块
String_labelStartByte3=起始字节

String_labellabel6bytemfkey3=6字节MF密钥
String_labelOutFormat3=输出格式
String_labelCardMode3=读卡模式

String_WiegandMode3=韦根模式

String_labelErrorWarning3=是否警告
String_labelWiegandMode3=韦根模式
String_labelPulseWidth3=脉冲宽度
String_labelPulseGap3=脉冲间隙

String_labelmac=MAC地址
String_labelReaderIP=读头地址
String_labelReaderPort=端口
String_labelServerIP=服务器IP
String_labelServerPort=端口
String_labelGateway=网关IP
String_labelSubnetIP=子网掩码

String_labelCheck3=是否校验

String_checkBox1=CPU卡
String_checkBox2=MF卡
String_checkBox3=身份证
String_checkBox4=ISO15693
String_checkBox5=IClass
String_checkBox6=Felica

String_PhysicalCardID=物理卡号
String_CardContent=内容

String_WriteConfig=写配置
String_ReadConfig=读配置

String_comboBoxFormat0=正向输出
String_comboBoxFormat1=反向输出

String_labelHeartbeat=心跳


;tabPage4


String_labelName2=姓名
String_labelSex2=性别
String_labelNation2=民族
String_labelyear2=年
String_labelmonth2=月
String_labelday2=日
String_labelBir=出生
String_labelAddress2=地址
String_labelIDNum2=公民身份证号
String_labelIssue2=签发机关
String_labelTerm=有效期限
String_buttonReadCardAuto=开始读卡
String_StopReadCard=停止读卡

String_comboBox10=文字+照片
String_comboBox11=文字+照片+指纹
String_comboBox12=物理卡号



;tabPage5

String_buttonWrtiteRTCTime=写RTC时间
String_buttonWriteCurrentRTCTime=实时写RTC时间
String_buttonReadRTCTime=读RTC时间
String_buttonOpen=远程开门
String_buttonClose=远程关门

String_buttonPlayVoice=语音播放
String_buttonSaveVoice=保存开门语音
String_buttonReadVoice=读出开门语音

String_comboBoxVoiceType0=开门语音
String_comboBoxVoiceType1=开机语音
String_comboBoxVoiceType2=未注册语音
String_comboBoxVoiceType3=次数用尽语音
String_comboBoxVoiceType4=已过期语音

String_labelOperatingCode=操作码
String_labelTextData=文本数据
String_labelVoiceType=语音类型


;Mifare Card

String_groupBox1=用户卡初始化
;Read|Write User Card ID
String_groupBox2=读写用户卡ID

String_labelSector=扇区
String_labelOld6key=旧密钥
String_labelNew6Key=新密钥
String_buttonModeifyKey=修改密钥
String_buttonReadUserID=读用户ID
String_buttonWrtiteUserID=写用户ID
String_labelMFKey1=6字节密钥
String_labelMFUserID=用户ID(十进制)


String_groupBox6=用户卡初始化
String_groupBox4=用户卡读写操作

String_labelMFKey1==6字节密钥
String_labelStartBlock1=起始块
String_labelStartByte1=起始字节
String_labelMFUserID=用户卡ID(十进制)
String_labelUserID=用户卡ID(十进制)

;cpu user card
String_groupBox6=用户卡初始化
String_groupBox4=用户卡读写操作

String_labelFileID=文件ID(十进制)
String_labelOld16Key=16字节旧密钥
String_labelNew16Key=16字节新密钥
String_labelUserKey2=16字节用户密钥
String_labelUserID2=用户ID(十进制)


String_buttonInitCPUUserCard=用户卡初始化
String_buttonRecoveryCPUUserCard=恢复用户卡
String_buttonReadCPUUserID=读用户卡
String_buttonWrtiteCPUUserID=写用户卡


String_buttonWriteCPUUserCardLoop=批量发卡
String_StopSendCard=停止


;config card

String_labelUserKey=用户卡密钥
String_labelFileID2=文件编号(十进制)

String_labelstartblock2=起始块
String_labelStartByte2=起始字节

String_label6bytemfkey=6字节MF密钥
String_labelOutFormat=输出格式
String_labelCardMode=读卡模式
String_labelErrorWarning=是否警告
String_labelWiegandMode=韦根模式
String_labelPulseWidth=脉冲宽度
String_labelPulseGap=脉冲间隙
String_labelCheck=是否校验


;button
String_buttonInitCofigCard=初始化配置卡
String_buttonRecoveryCard=恢复配置卡
String_buttonWrtiteConfigCard=写配置卡
String_buttonReadConfigCard=读配置卡

String_comboBoxFormat0=正向输出
String_comboBoxFormat1=反向输出


String_comboBoxCardMode0=CPU卡内容
String_comboBoxCardMode1=MF卡内容
String_comboBoxCardMode2=CPU内容+MF内容
String_comboBoxCardMode3=MF+CPU+身份证物理卡号
String_comboBoxCardMode4=MF物理卡号
String_comboBoxCardMode5=CPU+身份证物理卡号
String_comboBoxCardMode6=定制版读卡模式
String_comboBoxCardMode7=读招行卡模式
String_comboBoxCardMode8=迪科网络CPU卡
String_comboBoxCardMode9=自定义选择


;FM1208 MESSAGE ERROR

MESSAGE_ERROR_6981=命令和文件结构不相容！
MESSAGE_ERROR_6982=不满足安全状态！
MESSAGE_ERROR_6983=密钥被锁死！
MESSAGE_ERROR_6985=使用条件不满足！
MESSAGE_ERROR_63CX=密钥验证错误！请检查密钥是否正确！
MESSAGE_ERROR_6A80=数据域参数错误！
MESSAGE_ERROR_6A82=文件未找到！
MESSAGE_ERROR_6E00=无效CLA！
MESSAGE_ERROR_6700=长度错误！
MESSAGE_ERROR_CODE=错误代码：
MESSAGE_ERROR_83=没找到卡！
MESSAGE_ERROR_84=取随机数错误！


[StringLan]

String_ConnectOK=连接成功！
String_ConnectFail=连接失败！
String_DisConnectOK=断开成功！
String_DisConnectFail=断开失败！
String_PasswordLengthError=密钥长度错误!
String_ReadFail=读失败！
String_Address=地址: 
String_ReadCardFail=读卡失败！
String_DEMO_NAME=R400二维码读头 Demo

String_SendSuccess=发送成功!
String_SendFail=发送失败!
String_InitOK=发初始化成功!
String_IniFail=初始化失败!
String_QRCodeData=二维码数据：
String_HexCardData=16进制卡号数据：
String_CardData=卡号数据：
String_NoCardData=无数据！
String_Version=版本号：

String_SetOK=设置成功！
String_SetFail=设置失败！

String_AddressError=地址错误！

String_WriteOK=写成功!
String_WriteFail=写失败!

String_WriteCardFail=写卡失败!
String_WriteCardOK=写卡成功!

String_ModifyFail=修改失败!
String_ModifyOK=修改成功!

String_ClearFail=清除失败!
String_ClearOK=清除成功!

String_DeleteFail=删除失败!
String_DeleteOK=删除成功!


String_HIDFormat=键盘格式： 
String_FormatError=格式错误！
String_OpenDoorTime=开门时间：
String_Second=秒

String_Decimal=十进制
String_Hex=十六进制

String_BCD=BCD格式
String_RS485Open=485通道为打开 
String_RS485Close=485通道为关闭 

String_HIDOpen=HID键盘为打开 
String_HIDClose=HID键盘为关闭 

String_AtuoWLOpen=打开网络主动上传
String_AtuoWLClose=关闭网络主动上传

String_Atuo485Open=打开485主动上传
String_Atuo485Close=关闭485主动上传


String_WorkMode0=一体机模式
String_WorkMode1=读头模式


String_DIDError=DID错误！
String_QRKey=二维码解码密钥：

String_HexFormat=hex格式
String_CharFormat=char格式

String_LightMode0=灯工作模式: 常亮
String_LightMode1=灯工作模式: 间歇
String_LightMode2=灯工作模式: 感应

String_UnencryptedTransmission=不加密透传
String_EncryptedTransmission=加密传输
String_ZKEncrypted=定制加密模式

String_QREffectiveTime=二维码有效时间:

String_NoOutputDID=不输出DID
String_OutputDID=输出DID

String_MACLengthError=MAC长度错误!
String_DFIDLengthError=文件长度错误!
String_FileIDLengthError=文件ID长度错误!



String_mac=MAC地址: 
String_ReaderIP=读头地址: 
String_ReaderPort=端口: 
String_ServerIP=服务器IP: 
String_ServerPort=端口: 
String_Gateway=网关IP: 
String_SubnetIP=子网掩码: 

String_labelHeartbeat=心跳：


String_UserKey=用户卡密钥：
String_FileID=文件编号(十六进制)：

String_DFID=DF DF ID(16进制)

String_StartBlock=起始块：
String_StartByte=起始字节：
String_6bytemfkey=6字节MF密钥：
String_OutFormat=输出格式：
String_CardMode=读卡模式：
String_WiegandMode=韦根模式：
String_PulseWidth=脉冲宽度:
String_PulseGap=脉冲间隙:
String_Wiegand=韦根: 
String_Microsecond=微秒

String_PositiveOutput=正向输出 
String_InvertedOutput=反向输出

String_NoWiegandCheck=韦根无校验
String_WiegandCheck=韦根有校验


String_CardMode0=CPU卡内容
String_CardMode1=MF卡内容
String_CardMode2=CPU内容+MF内容
String_CardMode3=MF+CPU+身份证物理卡号
String_CardMode4=MF物理卡号
String_CardMode5=CPU+身份证物理卡号
String_CardMode6=定制版读卡模式
String_CardMode7=读招行卡模式
String_CardMode8=迪科网络CPU卡
String_CardMode9=自定义选择:


String_CardModeYXXZ0=CPU卡优先
String_CardModeYXXZ1=MF卡优先

String_CardModeSFZEN0=身份证内容不开门
String_CardModeSFZEN1=身份证内容开门

String_CardModeICEN0=IC卡内容不开门
String_CardModeICEN1=IC卡内容开门




String_CPUPhysicalCardID=CPU卡物理卡号
String_MFPhysicalCardID=MF卡物理卡号
String_SFZPhysicalCardID=身份证物理卡号
String_ISO15693PhysicalCardID=ISO15693卡物理卡号
String_IClassPhysicalCardID=IClass卡物理卡号
String_FilecaPhysicalCardID=Fileca卡物理卡号


String_CPUCardContent=CPU卡内容
String_MFCardContent=MF卡内容
String_SFZCardContent=身份证内容
String_ISO15693CardContent=ISO15693卡内容


String_WriteConfigFail=写配置失败!
String_WriteConfigOK=写配置成功!

String_ModifyFail=修改失败!
String_ModifyOK=修改成功!


String_DeleteFail=修改失败!
String_DeleteOK=修改成功!

;一体机

String_UserID=用户ID: 

String_LogOffset=日志偏移量: 

String_LogUserID=用户ID: 

String_LogRecordTime=记录时间：

String_LogStause0=状态：正常
String_LogStause1=状态：未注册
String_LogStause2=状态：次数已用完
String_LogStause3=状态：已过期

String_EffectiveTimestamp=有效时间戳：
String_RecordTimestamp=记录时间：

String_To= 至 
String_YYTime=已用次数 ：
String_KYTime=可用次数 ：
String_UserNum=用户数量 ：

String_LogSize=日志大小 ：


String_RecordTimestamp=记录时间戳：


String_RTCTime=RTC 时间：

String_Sunday=星期天
String_Monday=星期一 
String_Tuesday=星期二
String_Wednesday=星期三
String_Thursday=星期四
String_Friday=星期五
String_Saturday=星期六

StringOperationFailed=操作失败！
StringSuccessfulOperation=操作成功！

String_PlayOK=播放成功！
String_PlayFail=播放失败！

String_SaveOK=保存成功！
String_SaveFail=保存失败！

String_DoorVoice=开门语音：
String_StartVoice=开机语音：
String_UnregisteredVoice=未注册语音：
String_TimeLimitVoice=次数用尽语音：
String_ExpiredVoice=已过期语音：



String_RecoveryCardOK=回收卡片成功
String_RecoveryCardFail=回收卡片失败！

String_ModeifyKeyOK=修改密钥成功！
String_ModeifyKeyFail=修改密钥失败！



String_InitCardFail=初始化卡片失败!
String_InitCardOK=初始化卡片成功!

String_InitOK=初始化成功！
String_InitFail=初始化失败！

String_CardID=卡号：

String_ValueOutRange=数值太大！


String_BatchWriteCard=批量发卡

String_PutOtherCard=此卡操作成功，请放另外一张卡！

String_PutNewCard=请放新卡！


[LanguageSelection]
LANGUAGE_INDEX=1
Explain=Explain: English LANGUAGE_INDEX=0; Chinese LANGUAGE_INDEX=1;

[SpecialParameters]
Explain=Do not modify this parameter;
SERIAL_NUMBERA=860001










